id: os_umask_configure
title: "Configure Umask"
discussion:
  Newly created files should only be writable by the owner. Non-group members should not have any access.
check: |
  /usr/bin/umask
result:
  string: 0027
fix: |
  [source,bash]
  ----
  /bin/launchctl config user umask 027
  ----
references:
  cce:
    - n/a
  cci: 
    - n/a
  800-53r4: 
    - n/a
  srg: 
    - n/a
  disa_stig: 
    - n/a
  800-171r2:
    - n/a
macOS:
  - "11.0"
tags:
  - 800-179_sslf
  - preliminary
mobileconfig: false
mobileconfig_info: